### ISSUE TITLE
Needs license file

### ISSUE THREAD

**Issue by snunez1** [inaimathi/house#14]
Unlicensed and copyleft projects are generally forbidden in commercial projects. Please consider adding a (MIT preferably!) license to the project.

**Comment by PuercoPop** [comment]
Although the LICENSE file is missing the author has specified the license in the system definition. AGPLv3 https://github.com/inaimathi/house/blob/ba30a381670c681fa722c22c5a03f329d4c67c2e/house.asd#L7

**Comment by inaimathi** [comment]
Added in https://github.com/inaimathi/house/commit/96df9e7ad86fa12d29521bcd3e890662abcfe389

I prefer AGPL3 for server stuff, because I don't like the idea of someone customizing an implementation of House in order to tivoize something, and this offers at least minimal defense against it.
