### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by m-n** [inaimathi/house#3]
Have you considered the "default handler" idiom for addressing the issue outlined in http://langnostic.inaimathi.ca/article?name=i-liiiiive.html ?

In short it goes like this:

```
(handler-bind ((error (lambda (c)
                        ;; Give outer handlers first shot at handling
                        ;; the error.
                        (signal c)
                        ;; We only get here if they decline to handle.
                        (invoke-restart 'foo))))
  (bar))
```

(I think this pattern may be somewhat obscure. I learned about it from the section "Default Handling" of [this](http://www.nhplace.com/kent/Papers/Condition-Handling-2001.html) Kent Pitman paper.)

**Comment by Inaimathi** [comment]
Wasn't even aware that this was a pattern, to be honest. I'll read up on it. The part that feels dirty is that it looks like I'll have to do something along the lines of dispatching on the error message when a `simple-error` gets signaled.

**Comment by m-n** [comment]
That depends on exactly what your requirements are, but making assumptions about them with a bias towards "easy to implement", I don't think so. Just start the error reporting handler by re-`signal`-ing the condition. If there is another handler for the condition (e.g. to deal with interrupts), that handler will run. Otherwise the added `signal` call will have no noticeable effect and your logging code can run.

**Comment by m-n** [comment]
I'm afraid I've sent you on a wrong path. At a bare repl the interrupt seems to only trigger the debugger due to being unhandled, so this trick won't have an effect. In SLIME, I wasn't able to prevent the interrupt from landing me in the debugger no matter what handlers I put in place (running a threaded SBCL on Linux).
